import math
import typing

import numpy as np

from .dataset import Dataset
from .ops import Op


class Batch:
    '''
    A (mini)batch generated by the batch generator.
    '''

    def __init__(self):
        '''
        Ctor.
        '''

        self.data = None
        self.label = None
        self.idx = None


class BatchGenerator:
    '''
    Batch generator.
    Returned batches have the following properties:
      data: numpy array holding batch data of shape (s, SHAPE_OF_DATASET_SAMPLES).
      label: numpy array holding batch labels of shape (s, SHAPE_OF_DATASET_LABELS).
      idx: numpy array with shape (s,) encoding the indices of each sample in the original dataset.
    '''

    def __init__(self, dataset: Dataset, num: int, shuffle: bool, op: Op = None):
        '''
        Ctor.
        Dataset is the dataset to iterate over.
        num is the number of samples per batch. the number in the last batch might be smaller than that.
        shuffle controls whether the sample order should be preserved or not.
        op is an operation to apply to input samples.
        Raises TypeError on invalid argument types.
        Raises ValueError on invalid argument values, such as if num is > len(dataset).
        '''

        if not isinstance(dataset, Dataset):
            raise TypeError("Invalid argument type for argument dataset")

        if not isinstance(num, int):
            raise TypeError("Invalid argument type for argument num")

        if not isinstance(shuffle, bool):
            raise TypeError("Invalid argument type for argument shuffle")

        if not callable(op) and op is not None:
            raise TypeError("Invalid argument type for argument op")

        if num > len(dataset):
            raise ValueError("Batch size must not be larger than dataset length")

        self.dataset = dataset
        self.shuffle = shuffle
        self.op = op if op is not None else lambda x: x
        self.num_batches = math.ceil(len(self.dataset) / num)
        self.batches_idx_boundaries = np.arange(num, len(self.dataset), num)

        # prepare dataset for batch creation
        data = []
        labels = []
        idxs = []
        for i in np.arange(0, len(self.dataset)):
            sample = self.dataset[i]
            data.append(self.op(sample.data))
            labels.append(sample.label)
            idxs.append(sample.idx)
        self.data = np.array(data)
        self.labels = np.array(labels, dtype=np.int64)
        self.idxs = np.array(idxs, dtype=np.int64)

    def __len__(self) -> int:
        '''
        Returns the total number of batches the dataset is split into.
            This is identical to the total number of batches yielded every time the __iter__ method is called.
        '''

        return self.num_batches

    def __iter__(self) -> typing.Iterable[Batch]:
        '''
        Iterate over the wrapped dataset, returning the data as batches.
        '''
        idxs = np.random.permutation(self.idxs) if self.shuffle else self.idxs

        for batch_idxs in np.split(idxs, self.batches_idx_boundaries):
            batch = Batch()
            batch.data = self.data[batch_idxs]
            batch.label = self.labels[batch_idxs]
            batch.index = self.idxs[batch_idxs]

            yield batch
